#!/usr/bin/env bash
# Installing nginx (engine x)

apt-get update
apt-get -y install nginx

# Adding a HTML page

echo "Holberton School" > /var/www/html/index.html

# Checking if the service is running

state=$(pgrep nginx)

if [ -n "$state" ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
